### ISSUE TITLE
是否有计划兼容dtk5？20下无法编译

### ISSUE THREAD

**Issue by shenmo7192** [BLumia/deepin-terminal-ng#11]

**Comment by BLumia** [comment]
是编译的 master 分支吗？切到 `v20` 分支呢？

**Comment by SuperEndermanSM** [comment]
谢谢提醒，刚才是master分支，正在测试20分支

**Comment by SuperEndermanSM** [comment]
希望可以添加ctrl加拖动，拖动标签页
虽说完成度不是很高，但是非常好！很看好这个项目！将来deepin-terminal是否要用dtk版本代替现在的？

**Comment by BLumia** [comment]
> 将来deepin-terminal是否要用dtk版本代替现在的？

尽管这个 repo 是我的纯个人项目，事实上公司后续已经有在基于我这个 codebase 进行 DTK 版的新终端开发了，尽管和我自己的想法有比较大的区别，不过可以期待一下 Deepin 官方的 DTK 终端 :)

**Comment by BLumia** [comment]
一点点后续：

随着 deepin v20 社区版代码的推送逐步完成，deepin 官方的 DTK 终端的代码也已经释放了，可以见 https://github.com/linuxdeepin/deepin-terminal-reborn 。由于 Archlinux 中 DTK 也已经更新到 v20 对应的 5.x 版本，故这个项目也把主分支改为了 v20 适用的分支。

ps. 短期内我可能不太会有精力去持续维护这个项目了，如果您对 DTK 终端感兴趣的话，建议优先考虑看 deepin 官方所开发的那个，codebase 同样也是基于本项目的 :)
